apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tw3kda/PARCIAL_CHARTS_PATRONES-AVANZADOS.git   # cambia con tu repo real
    targetRevision: HEAD
    path: pedido-app
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pedido-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
